### ISSUE TITLE
scripts like natlinkconfig_gui may not be in path

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/natlink#146]
Regardless of whether python is installed for all or one user, we never really know where Scripts are going to be installed.

At install time, for the current user, we should add Scripts to the path in every case (installed python for current user or all users).

```
 >>> import sysconfig as s
>>> s.get_path("scripts")
'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32\\Scripts
```'

**Comment by LexiconCode** [comment]
The initial reasoning why it's not included is because another python install might be utilizing path other than what's used by the speech recognition stack. Therefore, shortcuts were created to launch the GUI/CLI which are under the natlink start menu.

I'm not really seeing much an advantage to adding it to path since users have access to those shortcuts.

**Comment by dougransom** [comment]
Ok seems reasonable to close.  I think it is more a python install issue.

**Comment by dougransom** [comment]
It is a python issue.  https://github.com/python/cpython/issues/90126
