### ISSUE TITLE
Setup: missing permissions for restricted user accounts

### ISSUE THREAD

**Issue by tripfish** [dictation-toolbox/natlink#166]
When running natlink setup (with a local administrator account), users with restricted permissions do not get access to the "c:\Program Files (x86)\Natlink\site-packages\" directory.

This results in the familiar {dd990001-bb89-11d2-b031-0060088dc929} message when Dragon starts.

It must be ensured during the installation that "computername\Users" also get permissions to the directory. Otherwise, no user with restricted permissions will be able to use natlink.

Reproduction steps:

- Create a user account (e.g. adminuser) that belongs to the Administrators group
- Create a user account that does not belong to any group and therefore has restricted permissions
- Log in with the restricted user
- Run the natlink setup
- Grant permission to run the setup with the local administrator account (adminuser).
- Complete the natlink configuration
- start Dragon

The message {dd990001-bb89-11d2-b031-0060088dc929} appears.
All users with restricted permissions do not have access to the "c:\Program Files (x86)\Natlink\site-packages\" directory.

**Comment by quintijn** [comment]
I was thinking, that setting permissions in the inno setup file could solve this. I am not familiar with restricted permissions though. 

But an adaptation to the file inno-setup-natlink.iss in the directory installersource of the natlink repository should possibly work.

**Comment by quintijn** [comment]
Sorry, I was misreading the issue. I will try the steps as described...

**Comment by tripfish** [comment]
Yes, everything will be installed correctly. However, it must be ensured that when creating the directory "c:\Program Files (x86)\Natlink" that all subdirs and files get Users read and execute permission.

Normally that can be done at iss with "Permissions: users-readexec". However, the directory or files do not appear to be created through the normal installation process. I couldn't find the right place, but I also don't have a working development or build environment to test it.

**Comment by dougransom** [comment]
from Sept 3 telegram chat:

https://github.com/dictation-toolbox/natlink/blob/dea86ad6b185cc5d23ec61ecd49103773927e98c/NatlinkSource/COM/appsupp.cpp#L78

Aaron Walker, [2023-09-03 3:01 AM]
That's my theory. Is there a read access permission error to the PYD.

Quintijn Hoogenboom, [2023-09-03 3:03 AM]
after renaming the HKLM/Natlink section

Aaron Walker, [2023-09-03 3:04 AM]
Does debug view provide anymore information?

Quintijn Hoogenboom, [2023-09-03 3:05 AM]
So indeed the error is with finding/starting the python interpreter.

Quintijn Hoogenboom, [2023-09-03 3:05 AM]
Maybe the Dragon log file?

Aaron Walker, [2023-09-03 3:06 AM]
HKEY_LOCAL_MACHINE

Aaron Walker, [2023-09-03 3:06 AM]
Technically this error happens before ever starting to try launching the interpreter

Aaron Walker, [2023-09-03 3:07 AM]
See

Aaron Walker, [2023-09-03 3:07 AM]
https://github.com/dictation-toolbox/natlink/blob/dea86ad6b185cc5d23ec61ecd49103773927e98c/NatlinkSource/COM/appsupp.cpp#L78

Aaron Walker, [2023-09-03 3:08 AM]
I know function fires early in the python initialization but it doesn't even get that far because it fails to read from the registry.

Aaron Walker, [2023-09-03 3:15 AM]
https://nsis-dev.github.io/NSIS-Forums/html/t-357148.html

Quintijn Hoogenboom, [2023-09-03 3:16 AM]
I was trying to change the rights of the natlink-5.5.5.dist-info folder. The folder natlink I did, but this dist-info folder fails.

Doug Ransom, [2023-09-13 10:12 AM]
https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-develop-custom-commands-application

Quintijn Hoogenboom, [2023-09-17 7:57 AM]
Doug, I would have some time tomorrow or tuesday to discuss the situation with the Unimacro PR and the privileges problem when starting Dragon/Natlink.

Doug Ransom, [2023-09-17 7:58 AM]
Ok, not sure which will work for me yet.  probably tuesday.

**Comment by dougransom** [comment]
I'll investigate further. It might be that a different place should be used for installing natlink.pyd for non-privleged installs.  c:\user\appdata\local\...  .

**Comment by dougransom** [comment]
@quintijn confirmed changing the permissions on subfolders fixed the problem.
I'll work on fixing the installer.

**Comment by dougransom** [comment]
with Inno:setup, Even if attempting to create folder with user permissions for read and execute for site-packages/natlink,  
pip changes the privileges.  

Also there is an __pycache__ folder in site-packages/natlink.  I don't think that will be an issue but who knows.

**Comment by quintijn** [comment]
Tried the installer you sent me, but no luck. No permissions propagating. Language settings all to English (Canada).
