### ISSUE TITLE
early warning when natlink installer detects a 64 bit python version

### ISSUE THREAD

**Issue by quintijn** [dictation-toolbox/natlink#6]
The supported python versions are (now) limited to 37-32 and 38-32. This can change, but especially if a 64 bit python version is running the config program (37-64 or 38-64), an unclear warning is given by the config program. 

It should be already in the start_natlinkconfigfunctions.py and start_natlinkconfig.py, but it was reported that this messages was not caught.

**Comment by quintijn** [comment]
I added code in start_configurenatlink.py, like was already in start_natlinkconfigfunctions.py.

What if a 64bit python version is on your system and the default. Will it be possible to go in elevated mode, look for the appropriate 32bit python version, if available, and run the natlinkconfigfunctions.py or configurenatlink.pyw in the 32bit version? Ideas about this?

Or do we just want a user with multiple python versions on his/her computer to start in the correct version right from the start?

**Comment by LexiconCode** [comment]
> What if a 64bit python version is on your system and the default. Will it be possible to go in elevated mode, look for the appropriate 32bit python version, if available, and run the natlinkconfigfunctions.py or configurenatlink.pyw in the 32bit version? Ideas about this?

I've looked into this for Caster. It's not an easy thing to do without digging into the registry and can be error-prone. I've had good success simply having a raised exception which is now integrated dragonfly to state that program is running on a 64-bit python instance and should be using 32-bit for Natlink.

**Comment by quintijn** [comment]
When you run via Dragon, the correct version of python is used, when the configure program did its work well, I believe. I was thinking that the configure program should be able to work with a 64 bit version of python, while targeting to the correct 32bit version. I can BTW give this a try...

**Comment by dougransom** [comment]
I think we can configure  the natlink package to only install in 32 bit python.  assign it to me and maybe i'll look at it someday.

**Comment by dougransom** [comment]
https://github.com/takluyver/flit/issues/425  hopefully there will be an answer and we can limit installs to 32 bit.

**Comment by dougransom** [comment]
ok, flit can't limit this.   See the response below.   

I m not really interested in maintaining a package for pip with setuptools, i am comfortable with flit as it is super-easy to  maintain.  So I suggest we allow pip to install on any architecture and let the config tool fail or provide a warning to the user.

@quintijn can you please assign this to yourself if you want to adjust the config tool, or to unassigned if there is nobody to address it?




_____________________________________________________________________________________________________________________________________

You can specify a Python version like requires-python = "~=3.8" in pyproject.toml. Flit doesn't and isn't likely to support restricting based on the architecture Python is compiled for, because it's aimed at pure Python packages where that shouldn't matter.
Using setuptools, you could reasonably publish wheels only for x86 (32-bit), and if you really wanted, check in setup.py to error out on 64-bit Python.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe. 
You can specify a Python version like requires-python = "~=3.8" in pyproject.toml. Flit doesn't and isn't likely to support restricting based on the architecture Python is compiled for, because it's aimed at pure Python packages where that shouldn't matter.
Using setuptools, you could reasonably publish wheels only for x86 (32-bit), and if you really wanted, check in setup.py to error out on 64-bit Python.
